### ISSUE TITLE
Trying to understand part of the code of office_wd.py ?

### ISSUE THREAD

**Issue by debasmitdas** [RockySJ/WDGRL#2]
In line 61 when you take gradients - 
gradients = tf.gradients(critic_out, [h2_whole])[0]

What is the role of [0] ?

**Comment by RockySJ** [comment]
The function tf.gradients returns a list. Please see the [API doc](https://www.tensorflow.org/api_docs/python/tf/gradients) .

**Comment by debasmitdas** [comment]
Yes, I get that but why do you just take the first element of the list.

**Comment by RockySJ** [comment]
tf.gradients() returns the gradients of the first argument with respect to each tensor in the second argument as a list in the order. There is only a tensor in the second argument in this line so there should be only one element in the return list, right?

**Comment by debasmitdas** [comment]
Yeah Agreed !!!
