### ISSUE TITLE
Trials for the experiments ?

### ISSUE THREAD

**Issue by debasmitdas** [RockySJ/WDGRL#3]
Are we using only a single trial for the experiments in the paper ? If so, why is that ? Is it because, we are using the whole dataset at once for the domain adaptation.

**Comment by RockySJ** [comment]
I am not quite sure about your question. What's the meaning of "a single trial" ?

**Comment by debasmitdas** [comment]
Normally, accuracy is reported by taking average over a number of trials of experiment. The trials correspond to random selection of the dataset. In your paper, how many trials did you use ?

**Comment by RockySJ** [comment]
Well, we report the highest accuracy on target test data for every adaptation task when tuning hyper-parameters.  And for every set of hyper-parameters, we only tried 1~3 times(trials?) of the current experiment to see the accuracy.

**Comment by debasmitdas** [comment]
OK. I see. Thanks for the information. It helps a lot. :)
