### ISSUE TITLE
mnist code

### ISSUE THREAD

**Issue by ltnn** [RockySJ/WDGRL#4]
Hi, I think you made a mistake in in mnist code. You put both source and target to train the classifier (use y_ instead of ys_true) so the result is 99.1%, which is too good to be true.

**Comment by RockySJ** [comment]
Thank you for your reminding. I have made a mistake here. I will refine this part of code and rerun the experiments.

**Comment by ltnn** [comment]
Thanks, btw, there is another interesting dataset: imageclef domain adaptation. You may like to test it, too. http://www.imageclef.org/2014/adaptation#test

**Comment by debasmitdas** [comment]
Isn't tf.slice is used to take only the source data labels ? I can't understand where he made the mistake.
